// <auto-generated />
using System;
using AdvancedProgramming_Lesson1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvancedProgramming_Lesson1.Migrations.MvcDrzewa
{
    [DbContext(typeof(MvcDrzewaContext))]
    [Migration("20230914135655_MvcDrzewa")]
    partial class MvcDrzewa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvancedProgramming_Lesson1.Models.Drzewa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_posadzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kolor_lisci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rodzaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Srednica_pnia")
                        .HasColumnType("int");

                    b.Property<int>("Wysokosc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Drzewa");
                });
#pragma warning restore 612, 618
        }
    }
}
